FROM mcr.microsoft.com/playwright/python:v1.52.0-noble

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN apt-get update \
    && apt-get install -y --no-install-recommends whois \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY . /app

ENV PYTHONUNBUFFERED=1
CMD ["celery", "-A", "workers.celery_app", "worker", "--loglevel=INFO", "--queues=celery", "--concurrency=2"]
