"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, MessageSquare, Plus, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import type { CrmMember, CrmTeam, Issue, IssueStatus } from "@/lib/crm-types";
import { cn } from "@/lib/utils";

const nextStatuses: Record<IssueStatus, IssueStatus[]> = { new: ["triaged"], triaged: ["assigned"], assigned: ["in_progress"], in_progress: ["blocked", "resolved"], blocked: ["in_progress", "resolved"], resolved: ["closed", "in_progress"], closed: ["in_progress"] };
async function requestJson(url: string, init?: RequestInit) { const response = await fetch(url, { cache: "no-store", ...init, headers: { "content-type": "application/json", ...(init?.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Request failed"); return body; }

export default function IssueDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [issue, setIssue] = useState<Issue | null>(null);
  const [current, setCurrent] = useState<CrmMember | null>(null);
  const [members, setMembers] = useState<CrmMember[]>([]);
  const [teams, setTeams] = useState<CrmTeam[]>([]);
  const [tab, setTab] = useState("Overview");
  const [owner, setOwner] = useState(""); const [team, setTeam] = useState(""); const [pm, setPm] = useState(""); const [em, setEm] = useState("");
  const [resolution, setResolution] = useState(""); const [comment, setComment] = useState(""); const [mentionIds, setMentionIds] = useState<string[]>([]); const [task, setTask] = useState("");
  const [severityEdit, setSeverityEdit] = useState("medium"); const [dueAt, setDueAt] = useState(""); const [overrideReason, setOverrideReason] = useState("");
  const [loading, setLoading] = useState(true);

  async function load() { setLoading(true); try { const [detail, directory] = await Promise.all([requestJson(`/api/issues/${id}`), requestJson("/api/issues/directory")]); setIssue(detail.issue); setCurrent(detail.currentMember); setMembers(directory.members || []); setTeams(directory.teams || []); setOwner(detail.issue.owner_id || ""); setTeam(detail.issue.team_id || ""); setPm(detail.issue.collaborators?.find((item: any) => item.responsibility === "pm")?.member_id || ""); setEm(detail.issue.collaborators?.find((item: any) => item.responsibility === "em")?.member_id || ""); setResolution(detail.issue.resolution_note || ""); setSeverityEdit(detail.issue.severity); setDueAt(detail.issue.due_at ? new Date(detail.issue.due_at).toISOString().slice(0, 16) : ""); setOverrideReason(detail.issue.sla_override_reason || ""); } catch (error: any) { toast.error(error.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [id]);
  async function mutate(body: any) { if (!issue) return; try { const result = await requestJson(`/api/issues/${id}`, { method: "PATCH", body: JSON.stringify({ ...body, expectedVersion: issue.version }) }); setIssue(result.issue); toast.success("Issue updated"); } catch (error: any) { toast.error(error.message); if (/changed by another/.test(error.message)) await load(); } }
  async function addComment() { if (!comment.trim()) return; try { await requestJson(`/api/issues/${id}/comments`, { method: "POST", body: JSON.stringify({ body: comment, mentionedMemberIds: mentionIds }) }); setComment(""); setMentionIds([]); await load(); } catch (error: any) { toast.error(error.message); } }
  async function addTask() { if (!task.trim()) return; try { await requestJson(`/api/issues/${id}/tasks`, { method: "POST", body: JSON.stringify({ title: task, assigneeId: owner || null }) }); setTask(""); await load(); } catch (error: any) { toast.error(error.message); } }
  async function updateTask(taskId: string, status: "open" | "in_progress" | "done", expectedVersion: number) { try { await requestJson(`/api/issues/${id}/tasks`, { method: "PATCH", body: JSON.stringify({ taskId, status, expectedVersion }) }); await load(); } catch (error: any) { toast.error(error.message); if (/changed by another/.test(error.message)) await load(); } }
  if (loading) return <div className="grid min-h-[60vh] place-items-center text-sm text-muted-foreground"><RefreshCw className="mr-2 inline h-4 w-4 animate-spin" />Loading issue…</div>;
  if (!issue || !current) return <div className="p-10 text-center">Issue not found.</div>;
  const manager = current.role === "admin" || current.role === "manager";
  const availableStatuses = nextStatuses[issue.status].filter((status) => manager || (issue.owner_id === current.id && !["triaged", "assigned", "closed"].includes(status) && !["resolved", "closed"].includes(issue.status)));
  return <div className="space-y-5">
    <header className="rounded-3xl border border-border bg-card p-6"><Link href="/issues" className="text-xs text-muted-foreground"><ArrowLeft className="mr-1 inline h-3.5 w-3.5" />Back to Issues</Link><div className="mt-5 flex flex-col gap-5 xl:flex-row xl:justify-between"><div><div className="flex flex-wrap gap-2"><Pill value={issue.severity} /><Pill value={issue.status} />{issue.source_platforms.map((item) => <Pill key={item} value={item} />)}</div><h1 className="mt-4 max-w-4xl text-3xl font-medium tracking-tight">{issue.title}</h1><p className="mt-2 max-w-4xl text-sm leading-relaxed text-muted-foreground">{issue.summary}</p><p className="mt-3 text-xs text-muted-foreground">Owner: {issue.owner?.display_name || "Unassigned"} · Team: {issue.team?.name || "Unassigned"} · Version {issue.version}</p></div><div className="min-w-[340px] rounded-2xl border border-border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Assignment</p><div className="mt-3 grid gap-2"><select value={owner} onChange={(e) => setOwner(e.target.value)} disabled={!manager} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="">Accountable owner</option>{members.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select><select value={team} onChange={(e) => setTeam(e.target.value)} disabled={!manager} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="">Owning team</option>{teams.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><select value={pm} onChange={(e) => setPm(e.target.value)} disabled={!manager} className="rounded-xl border border-border bg-background px-2 py-2 text-xs"><option value="">PM collaborator</option>{members.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select><select value={em} onChange={(e) => setEm(e.target.value)} disabled={!manager} className="rounded-xl border border-border bg-background px-2 py-2 text-xs"><option value="">EM collaborator</option>{members.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></div>{manager ? <button onClick={() => mutate({ action: "assign", ownerId: owner, teamId: team, collaborators: [{ memberId: pm, responsibility: "pm" }, { memberId: em, responsibility: "em" }].filter((item) => item.memberId) })} className="rounded-xl bg-black px-3 py-2 text-sm font-medium text-white">Save assignment</button> : null}</div></div></div></header>
    <section className="flex flex-wrap gap-2">{["Overview", "Evidence", "Tasks", "Comments", "Activity"].map((item) => <button key={item} onClick={() => setTab(item)} className={cn("rounded-full px-4 py-2 text-xs font-medium", tab === item ? "bg-black text-white" : "border border-border bg-card")}>{item}</button>)}</section>
    {tab === "Overview" ? <section className="grid gap-4 xl:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5 xl:col-span-2"><h2 className="font-semibold">Workflow</h2><p className="mt-1 text-xs text-muted-foreground">Only valid transitions are offered. Resolution and reopening require context.</p>{["resolved", "closed"].includes(issue.status) && manager ? <textarea value={resolution} onChange={(e) => setResolution(e.target.value)} placeholder="Reopen reason" className="mt-4 min-h-24 w-full rounded-xl border border-border bg-background p-3 text-sm" /> : (issue.status === "in_progress" || issue.status === "blocked") && (manager || issue.owner_id === current.id) ? <textarea value={resolution} onChange={(e) => setResolution(e.target.value)} placeholder="Resolution note required before resolving" className="mt-4 min-h-24 w-full rounded-xl border border-border bg-background p-3 text-sm" /> : null}<div className="mt-4 flex flex-wrap gap-2">{availableStatuses.map((status) => <button key={status} onClick={() => mutate({ action: "transition", status, resolutionNote: resolution, reason: ["resolved", "closed"].includes(issue.status) ? resolution : undefined })} className="rounded-xl border border-border px-4 py-2 text-xs font-semibold capitalize hover:bg-muted">Move to {status.replace(/_/g, " ")}</button>)}{!availableStatuses.length ? <p className="text-xs text-muted-foreground">No workflow action is available for your role.</p> : null}</div></div><div className="rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold">Priority & SLA</h2><p className="mt-4 text-xl font-medium">{issue.due_at ? new Date(issue.due_at).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Not set"}</p><p className="mt-1 text-xs text-muted-foreground">{issue.sla_overridden ? `Overridden: ${issue.sla_override_reason}` : "Calculated from issue priority"}</p>{manager ? <div className="mt-4 grid gap-2"><select value={severityEdit} onChange={(e) => setSeverityEdit(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm">{["critical", "high", "medium", "low"].map((item) => <option key={item}>{item}</option>)}</select><input type="datetime-local" value={dueAt} onChange={(e) => setDueAt(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm" /><input value={overrideReason} onChange={(e) => setOverrideReason(e.target.value)} placeholder="Reason required when overriding due date" className="rounded-xl border border-border bg-background px-3 py-2 text-xs" /><button onClick={() => mutate({ action: "edit", severity: severityEdit, dueAt: dueAt ? new Date(dueAt).toISOString() : undefined, overrideReason })} className="rounded-xl bg-black px-3 py-2 text-xs font-semibold text-white">Save priority and SLA</button></div> : null}</div></section> : null}
    {tab === "Evidence" ? <section className="grid gap-3 lg:grid-cols-2">{issue.evidence?.length ? issue.evidence.map((item: any) => <article key={item.id} className="rounded-2xl border border-border bg-card p-4"><div className="flex justify-between"><Pill value={item.platform} />{item.sentiment_label ? <Pill value={item.sentiment_label} /> : null}</div><blockquote className="mt-3 text-sm leading-relaxed">{item.content_text}</blockquote><p className="mt-3 text-xs text-muted-foreground">{item.author_label || "Unknown author"} · {item.published_at ? new Date(item.published_at).toLocaleDateString("en-IN") : "Date unavailable"}</p>{item.source_url ? <a href={item.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-medium underline">Open source</a> : null}</article>) : <Empty text="No evidence snapshots are attached." />}</section> : null}
    {tab === "Tasks" ? <section className="space-y-3">{manager || issue.owner_id === current.id ? <Composer value={task} setValue={setTask} placeholder="Add an actionable task" action="Add task" onSubmit={addTask} /> : null}{issue.tasks?.length ? issue.tasks.map((item: any) => <article key={item.id} className="flex items-start justify-between gap-4 rounded-2xl border border-border bg-card p-4"><div><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.assignee?.display_name || "Unassigned"}</p></div><div className="flex items-center gap-2"><Pill value={item.status} />{item.status !== "done" && (manager || item.assignee_id === current.id) ? <button onClick={() => updateTask(item.id, item.status === "open" ? "in_progress" : "done", item.version)} className="rounded-lg border border-border px-2 py-1 text-[10px] font-semibold">{item.status === "open" ? "Start" : "Complete"}</button> : null}</div></article>) : <Empty text="No tasks yet." />}</section> : null}
    {tab === "Comments" ? <section className="space-y-3"><div className="rounded-2xl border border-border bg-card p-4"><select value="" onChange={(event) => event.target.value && setMentionIds((currentIds) => Array.from(new Set([...currentIds, event.target.value])))} className="mb-3 rounded-xl border border-border bg-background px-3 py-2 text-xs"><option value="">Mention a teammate…</option>{members.filter((item) => item.active && !mentionIds.includes(item.id)).map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select>{mentionIds.length ? <div className="mb-3 flex flex-wrap gap-2">{mentionIds.map((memberId) => <button key={memberId} onClick={() => setMentionIds((ids) => ids.filter((id) => id !== memberId))} className="rounded-full border border-border px-2 py-1 text-[10px]">@{members.find((item) => item.id === memberId)?.display_name} ×</button>)}</div> : null}<textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add context, decision, or update" className="min-h-20 w-full resize-y bg-transparent text-sm outline-none" /><button onClick={addComment} className="mt-2 rounded-xl bg-black px-4 py-2 text-xs font-semibold text-white"><Plus className="mr-1 inline h-3.5 w-3.5" />Comment</button></div>{issue.comments?.length ? issue.comments.map((item: any) => <article key={item.id} className="rounded-2xl border border-border bg-card p-4"><p className="text-xs font-semibold">{item.author?.display_name || "Former member"}</p><p className="mt-2 text-sm leading-relaxed">{item.body}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(item.created_at).toLocaleString("en-IN")}</p></article>) : <Empty text="No comments yet." />}</section> : null}
    {tab === "Activity" ? <section className="rounded-2xl border border-border bg-card p-5"><div className="space-y-5">{issue.events?.map((item: any) => <div key={item.id} className="flex gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-black" /><div><p className="text-sm font-medium">{item.detail}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString("en-IN")} · {item.event_type}</p></div></div>)}</div></section> : null}
  </div>;
}

function Pill({ value }: { value: string }) { return <span className="inline-flex rounded-full border border-border px-2 py-1 text-[10px] font-semibold capitalize">{value.replace(/_/g, " ")}</span>; }
function Composer({ value, setValue, placeholder, action, onSubmit }: any) { return <div className="rounded-2xl border border-border bg-card p-4"><textarea value={value} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} className="min-h-20 w-full resize-y bg-transparent text-sm outline-none" /><button onClick={onSubmit} className="mt-2 rounded-xl bg-black px-4 py-2 text-xs font-semibold text-white"><Plus className="mr-1 inline h-3.5 w-3.5" />{action}</button></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground"><CheckCircle2 className="mx-auto mb-2 h-5 w-5" />{text}</div>; }
