"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Plus, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import type { CrmMember, CrmTeam } from "@/lib/crm-types";

async function api(init?: RequestInit) { const response = await fetch("/api/issues/directory", { cache: "no-store", ...init, headers: { "content-type": "application/json", ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Request failed"); return body; }
export default function DirectoryPage() {
  const [members, setMembers] = useState<CrmMember[]>([]); const [teams, setTeams] = useState<CrmTeam[]>([]); const [loading, setLoading] = useState(true);
  const [teamName, setTeamName] = useState(""); const [channel, setChannel] = useState("");
  const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState("member"); const [teamId, setTeamId] = useState(""); const [slack, setSlack] = useState("");
  async function load() { try { const data = await api(); setMembers(data.members || []); setTeams(data.teams || []); } catch (error: any) { toast.error(error.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function createTeam() { try { await api({ method: "POST", body: JSON.stringify({ type: "team", name: teamName, slackChannelId: channel }) }); setTeamName(""); setChannel(""); await load(); toast.success("Team added"); } catch (error: any) { toast.error(error.message); } }
  async function createMember() { try { await api({ method: "POST", body: JSON.stringify({ type: "member", email, displayName: name, role, teamId: teamId || null, slackUserId: slack || null }) }); setEmail(""); setName(""); setSlack(""); await load(); toast.success("Member added"); } catch (error: any) { toast.error(error.message); } }
  async function editMember(item: CrmMember) { const nextRole = window.prompt("Role: admin, manager, or member", item.role); if (!nextRole || !["admin", "manager", "member"].includes(nextRole)) return; const slackUserId = window.prompt("Slack user ID (optional)", item.slack_user_id || ""); try { await api({ method: "PATCH", body: JSON.stringify({ type: "member", id: item.id, role: nextRole, slack_user_id: slackUserId || null }) }); await load(); toast.success("Member updated"); } catch (error: any) { toast.error(error.message); } }
  async function editTeam(item: CrmTeam) { const slackChannelId = window.prompt("Slack channel ID (optional)", item.slack_channel_id || ""); if (slackChannelId === null) return; try { await api({ method: "PATCH", body: JSON.stringify({ type: "team", id: item.id, slack_channel_id: slackChannelId || null }) }); await load(); toast.success("Team updated"); } catch (error: any) { toast.error(error.message); } }
  if (loading) return <div className="grid min-h-[60vh] place-items-center"><RefreshCw className="h-5 w-5 animate-spin" /></div>;
  return <div className="space-y-5"><header><Link href="/issues" className="text-xs text-muted-foreground"><ArrowLeft className="mr-1 inline h-3.5 w-3.5" />Back to Issues</Link><h1 className="mt-4 text-4xl font-medium tracking-tight">Team directory</h1><p className="mt-2 text-sm text-muted-foreground">Manage workflow roles and Slack routing. Employees must sign in once with OTP before an admin can add them.</p></header>
    <section className="grid gap-4 xl:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold">Add team</h2><div className="mt-4 grid gap-2 sm:grid-cols-2"><input value={teamName} onChange={(e) => setTeamName(e.target.value)} placeholder="Team name" className="rounded-xl border border-border bg-background px-3 py-2 text-sm" /><input value={channel} onChange={(e) => setChannel(e.target.value)} placeholder="Slack channel ID" className="rounded-xl border border-border bg-background px-3 py-2 text-sm" /></div><button onClick={createTeam} className="mt-3 rounded-xl bg-black px-4 py-2 text-xs font-semibold text-white"><Plus className="mr-1 inline h-3.5 w-3.5" />Add team</button></div>
    <div className="rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold">Add member</h2><div className="mt-4 grid gap-2 sm:grid-cols-2"><input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="person@pw.live" className="rounded-xl border border-border bg-background px-3 py-2 text-sm" /><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Display name" className="rounded-xl border border-border bg-background px-3 py-2 text-sm" /><select value={role} onChange={(e) => setRole(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="member">Member</option><option value="manager">Manager</option><option value="admin">Admin</option></select><select value={teamId} onChange={(e) => setTeamId(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="">No team</option>{teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input value={slack} onChange={(e) => setSlack(e.target.value)} placeholder="Slack user ID" className="rounded-xl border border-border bg-background px-3 py-2 text-sm" /></div><button onClick={createMember} className="mt-3 rounded-xl bg-black px-4 py-2 text-xs font-semibold text-white"><Plus className="mr-1 inline h-3.5 w-3.5" />Add member</button></div></section>
    <section className="grid gap-4 xl:grid-cols-2"><div className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">Members</h2></div><div className="divide-y divide-border">{members.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="text-sm font-medium">{item.display_name}</p><p className="text-xs text-muted-foreground">{item.email} · {item.team?.name || "No team"} · {item.slack_user_id || "Slack unmapped"}</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-border px-2 py-1 text-[10px] font-semibold capitalize">{item.role}</span><button onClick={() => editMember(item)} className="text-xs font-medium underline">Edit</button></div></div>)}</div></div><div className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold">Teams</h2></div><div className="divide-y divide-border">{teams.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 px-5 py-4"><p className="text-sm font-medium">{item.name}</p><div className="flex items-center gap-2"><p className="text-xs text-muted-foreground">{item.slack_channel_id || "No Slack channel"}</p><button onClick={() => editTeam(item)} className="text-xs font-medium underline">Edit</button></div></div>)}</div></div></section>
  </div>;
}
